server:
  port: 8081

spring:
  application:
    name: acopio
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: acopio
    url: jdbc:mysql://localhost:3306/acopio
    username: root
    password: Holahola44#
