server:
  port: 8082

spring:
  application:
    name: grasas
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: grasas
    url: jdbc:mysql://localhost:3306/grasas
    username: root
    password: Holahola44#
